_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 12
                - 55
            "2":
                - 1
                - 12
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
K:
    value: 14
T:
    value: 243
batch_size:
    value: 8
lr:
    value: 0.05274762495168636
